[package]
name = "rust-ray-tracer"
version = "0.1.0"
authors = ["Jort van Gorkum <jortvangorkum@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "*"
nalgebra = "*"